<?php

declare(strict_types=1);

(static function (): void {
    $constants = [
        'Psl\Str\Internal\CASE_FOLD' => __DIR__ . '/Str/Internal/constants.php',
        'Psl\Str\ALPHABET' => __DIR__ . '/Str/constants.php',
    ];

    $functions = [
        'Psl\Str\Byte\after' => __DIR__ . '/Str/Byte/after.php',
        'Psl\Str\Byte\after_ci' => __DIR__ . '/Str/Byte/after_ci.php',
        'Psl\Str\Byte\after_last' => __DIR__ . '/Str/Byte/after_last.php',
        'Psl\Str\Byte\after_last_ci' => __DIR__ . '/Str/Byte/after_last_ci.php',
        'Psl\Str\Byte\before' => __DIR__ . '/Str/Byte/before.php',
        'Psl\Str\Byte\before_ci' => __DIR__ . '/Str/Byte/before_ci.php',
        'Psl\Str\Byte\before_last' => __DIR__ . '/Str/Byte/before_last.php',
        'Psl\Str\Byte\before_last_ci' => __DIR__ . '/Str/Byte/before_last_ci.php',
        'Psl\Str\Byte\capitalize' => __DIR__ . '/Str/Byte/capitalize.php',
        'Psl\Str\Byte\capitalize_words' => __DIR__ . '/Str/Byte/capitalize_words.php',
        'Psl\Str\Byte\chr' => __DIR__ . '/Str/Byte/chr.php',
        'Psl\Str\Byte\chunk' => __DIR__ . '/Str/Byte/chunk.php',
        'Psl\Str\Byte\compare' => __DIR__ . '/Str/Byte/compare.php',
        'Psl\Str\Byte\compare_ci' => __DIR__ . '/Str/Byte/compare_ci.php',
        'Psl\Str\Byte\contains' => __DIR__ . '/Str/Byte/contains.php',
        'Psl\Str\Byte\contains_ci' => __DIR__ . '/Str/Byte/contains_ci.php',
        'Psl\Str\Byte\ends_with' => __DIR__ . '/Str/Byte/ends_with.php',
        'Psl\Str\Byte\ends_with_ci' => __DIR__ . '/Str/Byte/ends_with_ci.php',
        'Psl\Str\Byte\length' => __DIR__ . '/Str/Byte/length.php',
        'Psl\Str\Byte\lowercase' => __DIR__ . '/Str/Byte/lowercase.php',
        'Psl\Str\Byte\ord' => __DIR__ . '/Str/Byte/ord.php',
        'Psl\Str\Byte\pad_left' => __DIR__ . '/Str/Byte/pad_left.php',
        'Psl\Str\Byte\pad_right' => __DIR__ . '/Str/Byte/pad_right.php',
        'Psl\Str\Byte\range' => __DIR__ . '/Str/Byte/range.php',
        'Psl\Str\Byte\replace' => __DIR__ . '/Str/Byte/replace.php',
        'Psl\Str\Byte\replace_ci' => __DIR__ . '/Str/Byte/replace_ci.php',
        'Psl\Str\Byte\replace_every' => __DIR__ . '/Str/Byte/replace_every.php',
        'Psl\Str\Byte\replace_every_ci' => __DIR__ . '/Str/Byte/replace_every_ci.php',
        'Psl\Str\Byte\reverse' => __DIR__ . '/Str/Byte/reverse.php',
        'Psl\Str\Byte\rot13' => __DIR__ . '/Str/Byte/rot13.php',
        'Psl\Str\Byte\search' => __DIR__ . '/Str/Byte/search.php',
        'Psl\Str\Byte\search_ci' => __DIR__ . '/Str/Byte/search_ci.php',
        'Psl\Str\Byte\search_last' => __DIR__ . '/Str/Byte/search_last.php',
        'Psl\Str\Byte\search_last_ci' => __DIR__ . '/Str/Byte/search_last_ci.php',
        'Psl\Str\Byte\shuffle' => __DIR__ . '/Str/Byte/shuffle.php',
        'Psl\Str\Byte\slice' => __DIR__ . '/Str/Byte/slice.php',
        'Psl\Str\Byte\splice' => __DIR__ . '/Str/Byte/splice.php',
        'Psl\Str\Byte\split' => __DIR__ . '/Str/Byte/split.php',
        'Psl\Str\Byte\starts_with' => __DIR__ . '/Str/Byte/starts_with.php',
        'Psl\Str\Byte\starts_with_ci' => __DIR__ . '/Str/Byte/starts_with_ci.php',
        'Psl\Str\Byte\strip_prefix' => __DIR__ . '/Str/Byte/strip_prefix.php',
        'Psl\Str\Byte\strip_suffix' => __DIR__ . '/Str/Byte/strip_suffix.php',
        'Psl\Str\Byte\trim' => __DIR__ . '/Str/Byte/trim.php',
        'Psl\Str\Byte\trim_left' => __DIR__ . '/Str/Byte/trim_left.php',
        'Psl\Str\Byte\trim_right' => __DIR__ . '/Str/Byte/trim_right.php',
        'Psl\Str\Byte\uppercase' => __DIR__ . '/Str/Byte/uppercase.php',
        'Psl\Str\Byte\words' => __DIR__ . '/Str/Byte/words.php',
        'Psl\Str\Byte\wrap' => __DIR__ . '/Str/Byte/wrap.php',
        'Psl\Str\Grapheme\after' => __DIR__ . '/Str/Grapheme/after.php',
        'Psl\Str\Grapheme\after_ci' => __DIR__ . '/Str/Grapheme/after_ci.php',
        'Psl\Str\Grapheme\after_last' => __DIR__ . '/Str/Grapheme/after_last.php',
        'Psl\Str\Grapheme\after_last_ci' => __DIR__ . '/Str/Grapheme/after_last_ci.php',
        'Psl\Str\Grapheme\before' => __DIR__ . '/Str/Grapheme/before.php',
        'Psl\Str\Grapheme\before_ci' => __DIR__ . '/Str/Grapheme/before_ci.php',
        'Psl\Str\Grapheme\before_last' => __DIR__ . '/Str/Grapheme/before_last.php',
        'Psl\Str\Grapheme\before_last_ci' => __DIR__ . '/Str/Grapheme/before_last_ci.php',
        'Psl\Str\Grapheme\contains' => __DIR__ . '/Str/Grapheme/contains.php',
        'Psl\Str\Grapheme\contains_ci' => __DIR__ . '/Str/Grapheme/contains_ci.php',
        'Psl\Str\Grapheme\ends_with' => __DIR__ . '/Str/Grapheme/ends_with.php',
        'Psl\Str\Grapheme\ends_with_ci' => __DIR__ . '/Str/Grapheme/ends_with_ci.php',
        'Psl\Str\Grapheme\length' => __DIR__ . '/Str/Grapheme/length.php',
        'Psl\Str\Grapheme\range' => __DIR__ . '/Str/Grapheme/range.php',
        'Psl\Str\Grapheme\reverse' => __DIR__ . '/Str/Grapheme/reverse.php',
        'Psl\Str\Grapheme\search' => __DIR__ . '/Str/Grapheme/search.php',
        'Psl\Str\Grapheme\search_ci' => __DIR__ . '/Str/Grapheme/search_ci.php',
        'Psl\Str\Grapheme\search_last' => __DIR__ . '/Str/Grapheme/search_last.php',
        'Psl\Str\Grapheme\search_last_ci' => __DIR__ . '/Str/Grapheme/search_last_ci.php',
        'Psl\Str\Grapheme\slice' => __DIR__ . '/Str/Grapheme/slice.php',
        'Psl\Str\Grapheme\starts_with' => __DIR__ . '/Str/Grapheme/starts_with.php',
        'Psl\Str\Grapheme\starts_with_ci' => __DIR__ . '/Str/Grapheme/starts_with_ci.php',
        'Psl\Str\Grapheme\strip_prefix' => __DIR__ . '/Str/Grapheme/strip_prefix.php',
        'Psl\Str\Grapheme\strip_suffix' => __DIR__ . '/Str/Grapheme/strip_suffix.php',
        'Psl\Str\Internal\validate_offset' => __DIR__ . '/Str/Internal/validate_offset.php',
        'Psl\Str\after' => __DIR__ . '/Str/after.php',
        'Psl\Str\after_ci' => __DIR__ . '/Str/after_ci.php',
        'Psl\Str\after_last' => __DIR__ . '/Str/after_last.php',
        'Psl\Str\after_last_ci' => __DIR__ . '/Str/after_last_ci.php',
        'Psl\Str\before' => __DIR__ . '/Str/before.php',
        'Psl\Str\before_ci' => __DIR__ . '/Str/before_ci.php',
        'Psl\Str\before_last' => __DIR__ . '/Str/before_last.php',
        'Psl\Str\before_last_ci' => __DIR__ . '/Str/before_last_ci.php',
        'Psl\Str\capitalize' => __DIR__ . '/Str/capitalize.php',
        'Psl\Str\capitalize_words' => __DIR__ . '/Str/capitalize_words.php',
        'Psl\Str\chr' => __DIR__ . '/Str/chr.php',
        'Psl\Str\chunk' => __DIR__ . '/Str/chunk.php',
        'Psl\Str\concat' => __DIR__ . '/Str/concat.php',
        'Psl\Str\contains' => __DIR__ . '/Str/contains.php',
        'Psl\Str\contains_ci' => __DIR__ . '/Str/contains_ci.php',
        'Psl\Str\convert_encoding' => __DIR__ . '/Str/convert_encoding.php',
        'Psl\Str\detect_encoding' => __DIR__ . '/Str/detect_encoding.php',
        'Psl\Str\ends_with' => __DIR__ . '/Str/ends_with.php',
        'Psl\Str\ends_with_ci' => __DIR__ . '/Str/ends_with_ci.php',
        'Psl\Str\fold' => __DIR__ . '/Str/fold.php',
        'Psl\Str\format' => __DIR__ . '/Str/format.php',
        'Psl\Str\format_number' => __DIR__ . '/Str/format_number.php',
        'Psl\Str\from_code_points' => __DIR__ . '/Str/from_code_points.php',
        'Psl\Str\is_empty' => __DIR__ . '/Str/is_empty.php',
        'Psl\Str\is_utf8' => __DIR__ . '/Str/is_utf8.php',
        'Psl\Str\join' => __DIR__ . '/Str/join.php',
        'Psl\Str\length' => __DIR__ . '/Str/length.php',
        'Psl\Str\levenshtein' => __DIR__ . '/Str/levenshtein.php',
        'Psl\Str\lowercase' => __DIR__ . '/Str/lowercase.php',
        'Psl\Str\metaphone' => __DIR__ . '/Str/metaphone.php',
        'Psl\Str\ord' => __DIR__ . '/Str/ord.php',
        'Psl\Str\pad_left' => __DIR__ . '/Str/pad_left.php',
        'Psl\Str\pad_right' => __DIR__ . '/Str/pad_right.php',
        'Psl\Str\range' => __DIR__ . '/Str/range.php',
        'Psl\Str\repeat' => __DIR__ . '/Str/repeat.php',
        'Psl\Str\replace' => __DIR__ . '/Str/replace.php',
        'Psl\Str\replace_ci' => __DIR__ . '/Str/replace_ci.php',
        'Psl\Str\replace_every' => __DIR__ . '/Str/replace_every.php',
        'Psl\Str\replace_every_ci' => __DIR__ . '/Str/replace_every_ci.php',
        'Psl\Str\reverse' => __DIR__ . '/Str/reverse.php',
        'Psl\Str\search' => __DIR__ . '/Str/search.php',
        'Psl\Str\search_ci' => __DIR__ . '/Str/search_ci.php',
        'Psl\Str\search_last' => __DIR__ . '/Str/search_last.php',
        'Psl\Str\search_last_ci' => __DIR__ . '/Str/search_last_ci.php',
        'Psl\Str\slice' => __DIR__ . '/Str/slice.php',
        'Psl\Str\splice' => __DIR__ . '/Str/splice.php',
        'Psl\Str\split' => __DIR__ . '/Str/split.php',
        'Psl\Str\starts_with' => __DIR__ . '/Str/starts_with.php',
        'Psl\Str\starts_with_ci' => __DIR__ . '/Str/starts_with_ci.php',
        'Psl\Str\strip_prefix' => __DIR__ . '/Str/strip_prefix.php',
        'Psl\Str\strip_suffix' => __DIR__ . '/Str/strip_suffix.php',
        'Psl\Str\to_int' => __DIR__ . '/Str/to_int.php',
        'Psl\Str\trim' => __DIR__ . '/Str/trim.php',
        'Psl\Str\trim_left' => __DIR__ . '/Str/trim_left.php',
        'Psl\Str\trim_right' => __DIR__ . '/Str/trim_right.php',
        'Psl\Str\truncate' => __DIR__ . '/Str/truncate.php',
        'Psl\Str\uppercase' => __DIR__ . '/Str/uppercase.php',
        'Psl\Str\width' => __DIR__ . '/Str/width.php',
        'Psl\Str\width_slice' => __DIR__ . '/Str/width_slice.php',
        'Psl\Str\wrap' => __DIR__ . '/Str/wrap.php',
    ];

    foreach ($constants as $constant => $path) {
        if (defined($constant)) {
            continue;
        }

        require_once $path;
    }

    foreach ($functions as $function => $path) {
        if (function_exists($function)) {
            continue;
        }

        require_once $path;
    }
})();
