build: false

clone_depth: 1
clone_folder: C:\projects\psl

platform:
  - x86
  - x64

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y php -version 7.4.3
  - cd c:\tools\php74
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - cd C:\projects\psl
  - SET PATH=C:\tools\php74;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install

test_script:
  - php composer.phar test:unit
  - php composer.phar cs:check
  - php composer.phar type:check
  - php composer.phar security:analysis
