<?php

declare(strict_types=1);

namespace Psl\MIME\Tests\Unit\Multipart;

use PHPUnit\Framework\TestCase;
use Psl\IO;
use Psl\MIME\Headers;
use Psl\MIME\MultiPart\Alternative;
use Psl\MIME\MultiPart\Parser;
use Psl\MIME\Part\Part;

use function iterator_to_array;
use function strlen;

final class AlternativeBuilderTest extends TestCase
{
    public function testBoundary(): void
    {
        $builder = new Alternative('alt-boundary');

        static::assertSame('alt-boundary', $builder->boundary);
    }

    public function testAutoGeneratedBoundary(): void
    {
        $builder = new Alternative();

        static::assertNotEmpty($builder->boundary);
        static::assertSame(24, strlen($builder->boundary));
    }

    public function testMediaType(): void
    {
        $builder = new Alternative('alt-boundary');

        $type = $builder->mediaType;
        static::assertSame('multipart/alternative', $type->essence());
        static::assertSame('alt-boundary', $type->parameters->get('boundary'));
    }

    public function testWriteTwoParts(): void
    {
        $builder = new Alternative('alt-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([[
                'Content-Type',
                'text/plain; charset=utf-8',
            ]]), new IO\MemoryHandle('Hello, plain text')),
        );
        $builder->addPart(
            new Part(Headers::fromPairs([[
                'Content-Type',
                'text/html; charset=utf-8',
            ]]), new IO\MemoryHandle('<p>Hello, <b>HTML</b></p>')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('alt-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('text/plain', $parts[0]->mediaType->essence());
        static::assertSame('text/html', $parts[1]->mediaType->essence());
    }

    public function testWritePreservesOrder(): void
    {
        $builder = new Alternative('order-boundary');
        $builder->addPart(new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('first')));
        $builder->addPart(new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('second')));
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'text/enriched']]), new IO\MemoryHandle('third')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('order-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(3, $parts);
        static::assertSame('text/plain', $parts[0]->mediaType->essence());
        static::assertSame('text/html', $parts[1]->mediaType->essence());
        static::assertSame('text/enriched', $parts[2]->mediaType->essence());
    }

    public function testWriteEmpty(): void
    {
        $builder = new Alternative('empty-boundary');

        $body = $builder->body()->readAll();
        static::assertStringContainsString('--empty-boundary--', $body);
    }

    public function testAsNestedPart(): void
    {
        $builder = new Alternative('nested-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('plain version')),
        );
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<p>html version</p>')),
        );

        static::assertSame('multipart/alternative', $builder->mediaType->essence());
        static::assertSame('nested-boundary', $builder->mediaType->parameters->get('boundary'));

        $parser = new Parser('nested-boundary');
        $inner = iterator_to_array($parser->parse($builder->body()));

        static::assertCount(2, $inner);
        static::assertSame('text/plain', $inner[0]->mediaType->essence());
        static::assertSame('text/html', $inner[1]->mediaType->essence());
    }

    public function testRoundTrip(): void
    {
        $builder = new Alternative('rt-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([[
                'Content-Type',
                'text/plain; charset=utf-8',
            ]]), new IO\MemoryHandle('Plain text body')),
        );
        $builder->addPart(
            new Part(Headers::fromPairs([[
                'Content-Type',
                'text/html; charset=utf-8',
            ]]), new IO\MemoryHandle('<html><body>HTML body</body></html>')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('rt-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertSame('Plain text body', $parts[0]->body->readAll());
        static::assertSame('<html><body>HTML body</body></html>', $parts[1]->body->readAll());
    }
}
