<?php

declare(strict_types=1);

namespace Psl\MIME\Tests\Unit\Multipart;

use PHPUnit\Framework\TestCase;
use Psl\IO;
use Psl\MIME\Headers;
use Psl\MIME\MultiPart\Form;
use Psl\MIME\MultiPart\Parser;
use Psl\MIME\Part\Part;
use Psl\Str\Byte;

use function iterator_to_array;

final class FormDataTest extends TestCase
{
    public function testAddField(): void
    {
        $form = new Form('test-boundary');
        $form->addField('username', 'alice');

        $body = $form->body()->readAll();
        static::assertStringContainsString('name=username', $body);
        static::assertStringContainsString('alice', $body);
    }

    public function testAddMultipleFields(): void
    {
        $form = new Form('boundary123');
        $form->addField('field1', 'value1');
        $form->addField('field2', 'value2');

        $output = new IO\MemoryHandle();
        IO\copy($form->body(), $output);

        $parser = new Parser('boundary123');
        $output->seek(0);
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('value1', $parts[0]->body->readAll());
        static::assertSame('value2', $parts[1]->body->readAll());
    }

    public function testAddPart(): void
    {
        $form = new Form('part-boundary');
        $part = new Part(Headers::fromPairs([[
            'Content-Type',
            'application/json',
        ]]), new IO\MemoryHandle('{"key":"value"}'));
        $form->addPart('data', $part);

        $body = $form->body()->readAll();
        static::assertStringContainsString('name=data', $body);
        static::assertStringContainsString('application/json', $body);
        static::assertStringContainsString('{"key":"value"}', $body);
    }

    public function testMediaType(): void
    {
        $form = new Form('my-boundary');

        $type = $form->mediaType;
        static::assertSame('multipart/form-data', $type->essence());
        static::assertSame('my-boundary', $type->parameters->get('boundary'));
    }

    public function testBoundary(): void
    {
        $form = new Form('explicit');

        static::assertSame('explicit', $form->boundary);
    }

    public function testAutoGeneratedBoundary(): void
    {
        $form = new Form();

        static::assertNotEmpty($form->boundary);
        static::assertSame(24, Byte\length($form->boundary));
    }

    public function testRoundTrip(): void
    {
        $form = new Form('rt-boundary');
        $form->addField('name', 'Alice');
        $form->addField('message', 'Hello, World!');

        $output = new IO\MemoryHandle();
        IO\copy($form->body(), $output);

        $parser = new Parser('rt-boundary');
        $output->seek(0);
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);

        $dispositionValue0 = $parts[0]->headers->get('content-disposition');
        static::assertNotNull($dispositionValue0);
        static::assertSame('Alice', $parts[0]->body->readAll());

        $dispositionValue1 = $parts[1]->headers->get('content-disposition');
        static::assertNotNull($dispositionValue1);
        static::assertSame('Hello, World!', $parts[1]->body->readAll());
    }

    public function testAddFieldReturnsVoid(): void
    {
        $form = new Form();
        $form->addField('a', 'b');

        $body = $form->body()->readAll();

        static::assertStringContainsString('a', $body);
    }
}
