<?php

declare(strict_types=1);

namespace Psl\MIME\Tests\Unit\Multipart;

use PHPUnit\Framework\TestCase;
use Psl\IO;
use Psl\MIME\Headers;
use Psl\MIME\MultiPart\Alternative;
use Psl\MIME\MultiPart\Composite;
use Psl\MIME\MultiPart\Parser;
use Psl\MIME\Part\Part;

use function iterator_to_array;
use function strlen;

final class MixedBuilderTest extends TestCase
{
    public function testBoundary(): void
    {
        $body = new Part(Headers::default(), new IO\MemoryHandle(''));
        $builder = new Composite($body, 'mix-boundary');

        static::assertSame('mix-boundary', $builder->boundary);
    }

    public function testAutoGeneratedBoundary(): void
    {
        $body = new Part(Headers::default(), new IO\MemoryHandle(''));
        $builder = new Composite($body);

        static::assertNotEmpty($builder->boundary);
        static::assertSame(24, strlen($builder->boundary));
    }

    public function testMediaType(): void
    {
        $body = new Part(Headers::default(), new IO\MemoryHandle(''));
        $builder = new Composite($body, 'mix-boundary');

        $type = $builder->mediaType;
        static::assertSame('multipart/mixed', $type->essence());
        static::assertSame('mix-boundary', $type->parameters->get('boundary'));
    }

    public function testBodyPartComesFirst(): void
    {
        $body = new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('main body'));

        $builder = new Composite($body, 'order-boundary');
        $builder->addPart(new Part(Headers::fromPairs([
            ['Content-Type',        'application/pdf'],
            ['Content-Disposition', 'attachment; filename="doc.pdf"'],
        ]), new IO\MemoryHandle('PDF-DATA')));

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('order-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('text/plain', $parts[0]->mediaType->essence());
        static::assertSame('application/pdf', $parts[1]->mediaType->essence());
    }

    public function testMultipleAttachments(): void
    {
        $body = new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<p>Hello</p>'));

        $builder = new Composite($body, 'multi-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'image/png']]), new IO\MemoryHandle('PNG-DATA')),
        );
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'application/zip']]), new IO\MemoryHandle('ZIP-DATA')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('multi-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(3, $parts);
        static::assertSame('text/html', $parts[0]->mediaType->essence());
        static::assertSame('image/png', $parts[1]->mediaType->essence());
        static::assertSame('application/zip', $parts[2]->mediaType->essence());
    }

    public function testBodyOnlyNoAttachments(): void
    {
        $body = new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('just a body'));

        $builder = new Composite($body, 'solo-boundary');

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('solo-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(1, $parts);
        static::assertSame('just a body', $parts[0]->body->readAll());
    }

    public function testAsNestedPart(): void
    {
        $body = new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('the body'));

        $builder = new Composite($body, 'nested-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'image/jpeg']]), new IO\MemoryHandle('JPEG-DATA')),
        );

        static::assertSame('multipart/mixed', $builder->mediaType->essence());
        static::assertSame('nested-boundary', $builder->mediaType->parameters->get('boundary'));

        $parser = new Parser('nested-boundary');
        $inner = iterator_to_array($parser->parse($builder->body()));

        static::assertCount(2, $inner);
        static::assertSame('text/plain', $inner[0]->mediaType->essence());
        static::assertSame('image/jpeg', $inner[1]->mediaType->essence());
    }

    public function testNestedAlternativeInMixed(): void
    {
        $alt = new Alternative('alt-boundary');
        $alt->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'text/plain']]), new IO\MemoryHandle('plain version')),
        );
        $alt->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<p>html version</p>')),
        );

        $altPart = new Part($alt->headers, new IO\MemoryHandle($alt->body()->readAll()));

        $builder = new Composite($altPart, 'mix-boundary');
        $builder->addPart(
            new Part(Headers::fromPairs([['Content-Type', 'application/pdf']]), new IO\MemoryHandle('PDF-ATTACHMENT')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('mix-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('multipart/alternative', $parts[0]->mediaType->essence());
        static::assertSame('application/pdf', $parts[1]->mediaType->essence());

        $firstBody = $parts[0]->body;

        $innerParser = new Parser('alt-boundary');
        $altParts = iterator_to_array($innerParser->parse($firstBody));

        static::assertCount(2, $altParts);
        static::assertSame('plain version', $altParts[0]->body->readAll());
        static::assertSame('<p>html version</p>', $altParts[1]->body->readAll());
    }

    public function testRoundTrip(): void
    {
        $body = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/plain; charset=utf-8',
        ]]), new IO\MemoryHandle('Message body content'));

        $builder = new Composite($body, 'rt-boundary');
        $builder->addPart(new Part(Headers::fromPairs([
            ['Content-Type',        'application/octet-stream'],
            ['Content-Disposition', 'attachment; filename="data.bin"'],
        ]), new IO\MemoryHandle('binary-data-here')));

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('rt-boundary');
        $parts = iterator_to_array($parser->parse($output));
        $firstBody = $parts[0]->body;
        $secondBody = $parts[1]->body;

        static::assertSame('Message body content', $firstBody->readAll());
        static::assertSame('binary-data-here', $secondBody->readAll());
    }
}
