<?php

declare(strict_types=1);

namespace Psl\MIME\Tests\Unit\Multipart;

use PHPUnit\Framework\TestCase;
use Psl\IO;
use Psl\MIME\ContentId;
use Psl\MIME\Headers;
use Psl\MIME\MultiPart\Alternative;
use Psl\MIME\MultiPart\Composite;
use Psl\MIME\MultiPart\Parser;
use Psl\MIME\MultiPart\Related;
use Psl\MIME\Part\Part;

use function iterator_to_array;
use function strlen;

final class RelatedBuilderTest extends TestCase
{
    public function testBoundary(): void
    {
        $root = new Part(Headers::default(), new IO\MemoryHandle(''));
        $builder = new Related($root, 'rel-boundary');

        static::assertSame('rel-boundary', $builder->boundary);
    }

    public function testAutoGeneratedBoundary(): void
    {
        $root = new Part(Headers::default(), new IO\MemoryHandle(''));
        $builder = new Related($root);

        static::assertNotEmpty($builder->boundary);
        static::assertSame(24, strlen($builder->boundary));
    }

    public function testMediaTypeIncludesTypeParameter(): void
    {
        $root = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html; charset=utf-8',
        ]]), new IO\MemoryHandle('<html></html>'));

        $builder = new Related($root, 'rel-boundary');

        $type = $builder->mediaType;
        static::assertSame('multipart/related', $type->essence());
        static::assertSame('rel-boundary', $type->parameters->get('boundary'));
        static::assertSame('text/html', $type->parameters->get('type'));
    }

    public function testRootPartComesFirst(): void
    {
        $root = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html',
        ]]), new IO\MemoryHandle('<html><img src="cid:img1@local"></html>'));

        $imageId = new ContentId('img1@local');
        $image = new Part(Headers::fromPairs([
            ['Content-Type', 'image/png'],
            ['Content-ID', $imageId->toString()],
        ]), new IO\MemoryHandle('PNG-DATA'));

        $builder = new Related($root, 'rel-boundary');
        $builder->addPart($image);

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('rel-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('text/html', $parts[0]->mediaType->essence());
        static::assertSame('image/png', $parts[1]->mediaType->essence());
    }

    public function testInlinePartPreservesContentId(): void
    {
        $root = new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<html></html>'));

        $id = ContentId::generate();
        $image = new Part(Headers::fromPairs([
            ['Content-Type', 'image/jpeg'],
            ['Content-ID', $id->toString()],
        ]), new IO\MemoryHandle('JPEG-DATA'));

        $builder = new Related($root, 'cid-boundary');
        $builder->addPart($image);

        $body = $builder->body()->readAll();
        static::assertStringContainsString('Content-ID: <' . $id->id . '>', $body);
    }

    public function testAddInlinePartAddsContentId(): void
    {
        $root = new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<html></html>'));

        $id = new ContentId('img1@local');
        $image = new Part(Headers::fromPairs([['Content-Type', 'image/png']]), new IO\MemoryHandle('PNG-DATA'));

        $builder = new Related($root, 'cid-boundary');
        $builder->addInlinePart($id, $image);

        $body = $builder->body()->readAll();
        static::assertStringContainsString('Content-ID: <img1@local>', $body);
    }

    public function testMultipleInlineParts(): void
    {
        $root = new Part(Headers::fromPairs([['Content-Type', 'text/html']]), new IO\MemoryHandle('<html></html>'));

        $builder = new Related($root, 'multi-boundary');
        $builder->addInlinePart(
            new ContentId('img1@local'),
            new Part(Headers::fromPairs([['Content-Type', 'image/png']]), new IO\MemoryHandle('PNG1')),
        );
        $builder->addInlinePart(
            new ContentId('img2@local'),
            new Part(Headers::fromPairs([['Content-Type', 'image/gif']]), new IO\MemoryHandle('GIF1')),
        );

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('multi-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(3, $parts);
    }

    public function testRootOnlyNoInlineParts(): void
    {
        $root = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html',
        ]]), new IO\MemoryHandle('<html>no images</html>'));

        $builder = new Related($root, 'solo-boundary');

        $output = new IO\MemoryHandle();
        IO\copy($builder->body(), $output);

        $output->seek(0);
        $parser = new Parser('solo-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(1, $parts);
        static::assertSame('<html>no images</html>', $parts[0]->body->readAll());
    }

    public function testAsNestedPart(): void
    {
        $root = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html',
        ]]), new IO\MemoryHandle('<html><img src="cid:a@b"></html>'));

        $builder = new Related($root, 'nested-boundary');
        $builder->addPart(new Part(Headers::fromPairs([
            ['Content-Type', 'image/png'],
            ['Content-ID',   '<a@b>'],
        ]), new IO\MemoryHandle('PNG-DATA')));

        static::assertSame('multipart/related', $builder->mediaType->essence());
        static::assertSame('nested-boundary', $builder->mediaType->parameters->get('boundary'));

        $parser = new Parser('nested-boundary');
        $inner = iterator_to_array($parser->parse($builder->body()));

        static::assertCount(2, $inner);
        static::assertSame('text/html', $inner[0]->mediaType->essence());
        static::assertSame('image/png', $inner[1]->mediaType->essence());
    }

    public function testNestedInMixed(): void
    {
        $root = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html',
        ]]), new IO\MemoryHandle('<html><img src="cid:pic@local"></html>'));

        $related = new Related($root, 'rel-boundary');
        $related->addPart(new Part(Headers::fromPairs([
            ['Content-Type', 'image/png'],
            ['Content-ID',   '<pic@local>'],
        ]), new IO\MemoryHandle('PNG-DATA')));

        $relatedPart = new Part($related->headers, new IO\MemoryHandle($related->body()->readAll()));

        $mixed = new Composite($relatedPart, 'mix-boundary');
        $mixed->addPart(new Part(Headers::fromPairs([
            ['Content-Type',        'application/pdf'],
            ['Content-Disposition', 'attachment; filename="doc.pdf"'],
        ]), new IO\MemoryHandle('PDF-DATA')));

        $output = new IO\MemoryHandle();
        IO\copy($mixed->body(), $output);

        $output->seek(0);
        $parser = new Parser('mix-boundary');
        $parts = iterator_to_array($parser->parse($output));

        static::assertCount(2, $parts);
        static::assertSame('multipart/related', $parts[0]->mediaType->essence());
        static::assertSame('application/pdf', $parts[1]->mediaType->essence());

        $innerParser = new Parser('rel-boundary');
        $relParts = iterator_to_array($innerParser->parse($parts[0]->body));

        static::assertCount(2, $relParts);
        static::assertSame('text/html', $relParts[0]->mediaType->essence());
        static::assertSame('image/png', $relParts[1]->mediaType->essence());
    }

    public function testFullEmailStructure(): void
    {
        $alt = new Alternative('alt-boundary');
        $alt->addPart(
            new Part(Headers::fromPairs([[
                'Content-Type',
                'text/plain',
            ]]), new IO\MemoryHandle('Plain text with image reference')),
        );

        $htmlRoot = new Part(Headers::fromPairs([[
            'Content-Type',
            'text/html',
        ]]), new IO\MemoryHandle('<html><img src="cid:logo@corp"></html>'));

        $related = new Related($htmlRoot, 'rel-boundary');
        $related->addPart(new Part(Headers::fromPairs([
            ['Content-Type', 'image/png'],
            ['Content-ID',   '<logo@corp>'],
        ]), new IO\MemoryHandle('LOGO-PNG')));

        $relatedPart2 = new Part($related->headers, new IO\MemoryHandle($related->body()->readAll()));
        $alt->addPart($relatedPart2);

        $altPart = new Part($alt->headers, new IO\MemoryHandle($alt->body()->readAll()));
        $mixed = new Composite($altPart, 'mix-boundary');
        $mixed->addPart(new Part(Headers::fromPairs([
            ['Content-Type',        'application/zip'],
            ['Content-Disposition', 'attachment; filename="archive.zip"'],
        ]), new IO\MemoryHandle('ZIP-DATA')));

        $output = new IO\MemoryHandle();
        IO\copy($mixed->body(), $output);

        $output->seek(0);
        $mixedParts = iterator_to_array(new Parser('mix-boundary')->parse($output));
        static::assertCount(2, $mixedParts);
        static::assertSame('multipart/alternative', $mixedParts[0]->mediaType->essence());
        static::assertSame('application/zip', $mixedParts[1]->mediaType->essence());

        $altParts = iterator_to_array(new Parser('alt-boundary')->parse($mixedParts[0]->body));
        static::assertCount(2, $altParts);
        static::assertSame('text/plain', $altParts[0]->mediaType->essence());
        static::assertSame('multipart/related', $altParts[1]->mediaType->essence());

        $relParts = iterator_to_array(new Parser('rel-boundary')->parse($altParts[1]->body));
        static::assertCount(2, $relParts);
        static::assertSame('text/html', $relParts[0]->mediaType->essence());
        static::assertSame('image/png', $relParts[1]->mediaType->essence());
    }
}
