name: audit repositories

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    name: audit organization repositories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: bcmath, mbstring, intl, sodium, json, openssl
          coverage: none

      - uses: extractions/setup-just@v3

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.SPLIT_APP_ID }}
          private-key: ${{ secrets.SPLIT_APP_PRIVATE_KEY }}
          owner: php-standard-library

      - run: just install

      - run: just split-install

      - run: just split-audit
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
