name: "security analysis"

on:
  pull_request: ~
  push: ~

jobs:
  security-analysis:
    name: "security analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@2.11.0"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "installing dependencies"
        run: |
          make install-root-dependencies
          make install-static-analysis-dependencies

      - name: "running security analysis ( psalm )"
        run: make security-analysis
