name: "static analysis"

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: '0 */3 * * *'

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "installing dependencies"
        run: |
          make install -j10 -O

      - name: "running static analysis"
        run: make static-analysis

      - name: "calculating type coverage"
        run: make type-coverage
