name: "static analysis"

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: '0 */3 * * *'

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: setup
        uses: ./.github/actions/setup
        with:
          php: "8.1"
          os: "ubuntu-latest"

      - name: "running static analysis"
        run: make static-analysis

      - name: "running security analysis"
        run: make security-analysis

      - name: "calculating type coverage"
        run: make type-coverage
