name: "unit tests"

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    name: "unit tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          # MacOs has a floating-point problem.
          # - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "caching dependencies"
        uses: "actions/cache@v3"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}"
          restore-keys: "php-${{ matrix.php-version }}"

      - name: "installing dependencies"
        run: |
          make install -j10

      - name: "running unit tests"
        run: ./vendor/bin/phpunit -c config/phpunit.xml.dist
